# Да простят меня боги программирования за то что храню такую инфу в конфиге
token: "vk1.a.QI8I8xl-Be6DbqyRbj16Wsc7HHhc84ONbDNVcGJdv6OFu07sJOLjgIap7x5aYL_-Wqnwv9qHpOkbPggxXkJl7gmzpkojHapGsn1k8j2YGKc4XcGIiBQaNfQuzYIu_z7wqnwJ-Vc6iqFy_ZYdXC7nNaAdUg1kDw3HrGS4G28Jfh9P1Icfwbl3I5XtY6FDUyozCt4yHi3Z-VkK1jEHPPeGJQ"

group_id: 224130500